# Sidebar navigation

- label: '简介'
  link: '/'
- label: 移植记录
  items:
    - label: 'latest'
      link: '/pages/latest'
    - label: '91版测试'
      link: '/pages/v91/build91'
- label: '依赖调整与准备'
  items:
    - label: 'rustc'
      link: '/pages/dep/rust-cross
    - label: '杂项调整'
      link: '/pages/dep/dep'
