# Sidebar navigation

- label: '简介'
  link: '/'
- label: 移植记录
  items:
    - label: 'latest'
      link: '/pages/latest'
    - label: '91版测试'
      link: '/pages/v91/build91'
- label: '依赖调整与准备'
  items:
    - label: 'rustc'
      link: '/pages/dep/rust-cross'
    - label: 'gcc13'
      link: '/pages/dep/gcc13'
    - label: 'nodejs'
      link: '/pages/dep/nodejs'
    - label: '杂项调整'
      link: '/pages/dep/dep'
- label: 'deb打包'
  items:
    - label: 'deb打包入门'
      link: '/pages/deb/start'
    - label: '为thunderbird打包deb包'
      link: '/pages/deb/thunderbird'
- label: 'Thunderbird'
  items:
    - label: 'Thunderbird'
      link: '/pages/thunderbird'
